config/routes.rb
Rails.application.routes.draw do
  
devise_for :admins
devise_for :users, controllers: {
		sessions: 'users/sessions'	
		}
    resources :zombies do
    resources :brains
    end
	
	devise_scope :admin do
		get "admins/users/list",
		to: "admins/sessions#list",
		as: "users_list"
	end
    root to: 'zombies#index'
    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
 
        
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
      
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

<div class="top-bar">
  <div class="top-bar-left">
      
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text"></li>
      <li>
        <a href="#">Zombie</a>
        <ul class="menu vertical">
           <li><%= link_to 'Lista Zombie', zombies_path %></li>
          <li><%= link_to 'Nuevo Zombie', new_zombie_path %></li>
        </ul>
      </li>
        
     
    </ul>
    </div>
      <div class="top-bar-right">
          <% if user_signed_in? %>
          <strong>Bienvenido(a) <%= current_user.email %> </strong>
          <strong><%= link_to "Cerrar Sesion", destroy_user_session_path, method: :delete %></strong>
          <strong><%= link_to "Editar Perfil", edit_user_registration_path %> </strong>
          <% else %>
          <strong><%= link_to "Login", new_user_session_path %></strong>
          <strong><%= link_to "Registrar", new_user_registration_path %></strong>
          
          <% end %>
</div>
  
</div>
     
      <%if alert%>
        <p class="alert alert-danger"><%= alert %></p><% end %>
 
      
    <%= yield %>
    
  </body>
</html>